from turtle import*
bgcolor("white")
pen(pencolor='red',fillcolor='red')
begin_fill()
pensize(5)
setposition(0,0)
left(50)
forward(133)
circle(50,200)
right(140)
circle(50,200)
forward(133)
end_fill()
pendown()
setposition(0,220)
write('Tanu',font=("Arial",18,"normal"),align="center")
title("Welcome to My Turtle Program")
hideturtle()
done()